#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Download the local OGC schema mirror into ogc_schemas/ and build schemas-extra/ (both git-ignored).

    scripts/fetch_ogc_schemas.py [--force]

ogc_schemas/ is the official SCHEMAS_OPENGIS_NET.zip, unpacked, plus the spec PDFs
the docs refer to, at its top level. scripts/schema_coverage.py reads it directly;
scripts/gdal mounts it read-only.

schemas-extra/ is what offline validation (scripts/validate-gml) needs on top:
  catalog.xml   XML catalog: schemas.opengis.net -> ../ogc_schemas/, W3C schemas -> w3c/
  w3c/          xlink.xsd and xml.xsd from www.w3.org (imported by GML 3.2 / WFS 2.0)
  ogc-xlink/    OGC xlink 1.0.0 (GML 2 / 3.1), shipped only zipped in ogc_schemas/xlink/

Existing files are kept unless --force is given; catalog.xml is always rewritten.
"""
import argparse
import io
import shutil
import sys
import tempfile
import urllib.request
import zipfile
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
OUT = PROJECT / "ogc_schemas"
EXTRA = PROJECT / "schemas-extra"
SCHEMAS_ZIP = "https://schemas.opengis.net/SCHEMAS_OPENGIS_NET.zip"
UA = {"User-Agent": "Mozilla/5.0 (xeibe fetch_ogc_schemas)"}

# (URL, file name in ogc_schemas/)
PDFS = [
    ("https://docs.ogc.org/is/02-069/02-069.pdf", "GML_2.1.2_02-069.pdf"),
    ("https://docs.ogc.org/is/07-036/07-036.pdf", "GML_3.2.1_07-036.pdf"),
    ("https://docs.ogc.org/profile/10-100r3/10-100r3.pdf", "GML_Simple-features-profile-2.0_10-100r3.pdf"),
    ("https://docs.ogc.org/is/02-058/02-058.pdf", "WFS_1.0.0_02-058.pdf"),
    ("https://docs.ogc.org/is/04-094/04-094.pdf", "WFS_1.1.0_04-094.pdf"),
    ("https://docs.ogc.org/is/09-025r1/09-025r1.pdf", "WFS_2.0_09-025r1.pdf"),
    ("https://docs.ogc.org/is/09-025r2/09-025r2.pdf", "WFS_2.0.2_09-025r2.pdf"),
    ("https://docs.ogc.org/is/09-026r2/09-026r2.pdf", "FES_2.0.2_09-026r2.pdf"),
    ("https://docs.ogc.org/is/06-121r9/06-121r9.pdf", "OWS-Common_2.0_06-121r9.pdf"),
    ("https://docs.ogc.org/bp/07-092r3/07-092r3.pdf", "URN-definitions_07-092r3.pdf"),
    ("https://docs.ogc.org/bp/11-135r2/11-135r2.pdf", "CRS-name-type_11-135r2.pdf"),
    ("https://docs.ogc.org/pol/09-048r7.pdf", "Name-type-def-part1_09-048r7.pdf"),
]
# GML 3.1.1 (03-105r1) is only published as a zip with the schemas and the PDF.
GML31_ZIP = ("https://docs.ogc.org/bp/03-105r1/03-105r1.zip", "GML-3.1.1/GML-3.1.pdf", "GML-3.1.pdf")

# (URL, file name in schemas-extra/w3c/)
W3C = [
    ("https://www.w3.org/1999/xlink.xsd", "xlink.xsd"),
    ("https://www.w3.org/2001/xml.xsd", "xml.xsd"),
]
OGC_XLINK_ZIP = "xlink/xlink-1_0_0.zip"  # in ogc_schemas/; unpacked to schemas-extra/ogc-xlink/

CATALOG = """<?xml version="1.0"?>
<!-- Generated by scripts/fetch_ogc_schemas.py; edit it there.
     XML catalog for offline schema validation with xmllint or lxml.
     Maps schemas.opengis.net to ../ogc_schemas/ and the W3C xlink/xml schemas to w3c/.
     Usage: scripts/validate-gml FILE... -->
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
  <!-- OGC xlink 1.0.0 (GML 2 / 3.1) is only shipped zipped in ogc_schemas/ -->
  <rewriteURI uriStartString="http://schemas.opengis.net/xlink/" rewritePrefix="ogc-xlink/xlink/"/>
  <rewriteSystem systemIdStartString="http://schemas.opengis.net/xlink/" rewritePrefix="ogc-xlink/xlink/"/>
  <rewriteURI uriStartString="http://schemas.opengis.net/" rewritePrefix="../ogc_schemas/"/>
  <rewriteSystem systemIdStartString="http://schemas.opengis.net/" rewritePrefix="../ogc_schemas/"/>
  <rewriteURI uriStartString="https://schemas.opengis.net/" rewritePrefix="../ogc_schemas/"/>
  <rewriteSystem systemIdStartString="https://schemas.opengis.net/" rewritePrefix="../ogc_schemas/"/>
  <uri name="http://www.w3.org/1999/xlink.xsd" uri="w3c/xlink.xsd"/>
  <system systemId="http://www.w3.org/1999/xlink.xsd" uri="w3c/xlink.xsd"/>
  <uri name="http://www.w3.org/2001/xml.xsd" uri="w3c/xml.xsd"/>
  <system systemId="http://www.w3.org/2001/xml.xsd" uri="w3c/xml.xsd"/>
</catalog>
"""


def fetch(url: str) -> bytes:
    print(f"downloading {url}", file=sys.stderr)
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=300) as r:
        return r.read()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--force", action="store_true", help="download everything again")
    args = ap.parse_args()

    if args.force or not (OUT / "gml").is_dir():
        data = fetch(SCHEMAS_ZIP)
        # Unpack next to the target, then swap, so an interrupted run leaves no half mirror.
        with tempfile.TemporaryDirectory(dir=PROJECT) as tmp:
            zipfile.ZipFile(io.BytesIO(data)).extractall(tmp)
            pdfs = list(OUT.glob("*.pdf")) if OUT.is_dir() else []
            for pdf in pdfs:
                shutil.move(pdf, Path(tmp) / pdf.name)
            if OUT.exists():
                shutil.rmtree(OUT)
            shutil.move(tmp, OUT)
            Path(tmp).mkdir()  # TemporaryDirectory cleans it up

    failed = 0
    for url, name in PDFS:
        target = OUT / name
        if target.exists() and not args.force:
            continue
        data = fetch(url)
        if not data.startswith(b"%PDF"):
            print(f"FAIL {name}: {url} did not return a PDF", file=sys.stderr)
            failed += 1
            continue
        target.write_bytes(data)

    url, member, name = GML31_ZIP
    if args.force or not (OUT / name).exists():
        (OUT / name).write_bytes(zipfile.ZipFile(io.BytesIO(fetch(url))).read(member))

    for url, name in W3C:
        target = EXTRA / "w3c" / name
        if target.exists() and not args.force:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(fetch(url))

    if args.force or not (EXTRA / "ogc-xlink").is_dir():
        if (EXTRA / "ogc-xlink").exists():
            shutil.rmtree(EXTRA / "ogc-xlink")
        zipfile.ZipFile(OUT / OGC_XLINK_ZIP).extractall(EXTRA / "ogc-xlink")

    (EXTRA / "catalog.xml").write_text(CATALOG)

    print(f"-> {OUT.relative_to(PROJECT)}/, {EXTRA.relative_to(PROJECT)}/", file=sys.stderr)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
