#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Regenerate the summary table in docs/support-matrix.md.

Counts status markers per level-2 section (## N. …) and rewrites the block between
<!-- summary:start --> and <!-- summary:end -->. Run after changing any status.
"""
import pathlib
import re

DOC = pathlib.Path(__file__).resolve().parent.parent / "docs" / "support-matrix.md"
STATUSES = [("✅", "Supported"), ("🚧", "In progress"), ("📋", "Planned"),
            ("🤔", "Considering"), ("❌", "Not planned")]

text = DOC.read_text(encoding="utf-8")
head, rest = text.split("<!-- summary:start -->", 1)
_, tail = rest.split("<!-- summary:end -->", 1)

rows, section = {}, None
for line in tail.splitlines():
    if m := re.match(r"^## (\d+\. .+)$", line):
        section = m.group(1)
        rows[section] = {icon: 0 for icon, _ in STATUSES}
    elif section and line.startswith("|") and not line.startswith("|---"):
        cells = [c.strip() for c in line.strip("|").split("|")]
        for icon, _ in STATUSES:
            if any(c.startswith(icon) for c in cells):
                rows[section][icon] += 1
                break

header = "| Section | " + " | ".join(f"{i} {n}" for i, n in STATUSES) + " | Progress |"
sep = "|---" * (len(STATUSES) + 2) + "|"
lines = [header, sep]
total = {icon: 0 for icon, _ in STATUSES}
for name, counts in rows.items():
    for k, v in counts.items():
        total[k] += v
    in_scope = counts["✅"] + counts["🚧"] + counts["📋"]
    pct = f"{100 * counts['✅'] // in_scope}%" if in_scope else "—"
    lines.append(f"| {name} | " + " | ".join(str(counts[i]) for i, _ in STATUSES) + f" | {pct} |")
in_scope = total["✅"] + total["🚧"] + total["📋"]
pct = f"{100 * total['✅'] // in_scope}%" if in_scope else "—"
lines.append("| **Total** | " + " | ".join(f"**{total[i]}**" for i, _ in STATUSES) + f" | **{pct}** |")
lines.append("")
lines.append("*Progress = ✅ / (✅ + 🚧 + 📋). Generated by `scripts/support_summary.py`.*")

DOC.write_text(head + "<!-- summary:start -->\n" + "\n".join(lines) + "\n<!-- summary:end -->" + tail,
               encoding="utf-8")
print("\n".join(lines))
