//! EPSG CRS facts and PROJJSON definitions, generated from the EPSG dataset.
//!
//! Two tables, with deliberately different shapes because they are used very
//! differently:
//!
//! * [`CRS`] holds the facts the axis-order decision needs ([`FirstAxis`],
//!   dimension, units, area of use). It is on the hot path, so it is a plain
//!   sorted `static` array: no decompression, no allocation, no lazy init.
//! * PROJJSON is needed once per geometry column, only when writing GeoArrow or
//!   GeoParquet metadata, and is far too big to hold uncompressed. It lives in
//!   a zstd-sharded blob that [`projjson`] decompresses one shard at a time.
//!
//! Everything here is generated by `scripts/gen_crs_tables.py` from an official
//! EPSG release. The data is IOGP's, not ours: see `EPSG-NOTICE.md`.
//!
//! No PROJ, GDAL or network access is involved, at build time or at run time.

use std::collections::HashMap;
use std::sync::{Mutex, OnceLock};

// Generated data: bbox values such as 3.14 are not π, and f32 literals keep
// the digits EPSG publishes.
#[allow(clippy::approx_constant, clippy::excessive_precision)]
mod table;

pub use table::{CRS, EPSG_DATE, EPSG_VERSION, PROJJSON_COUNT};

/// Direction of a CRS's first axis, in the authority's own axis order.
///
/// This is what decides whether coordinates written in authority order need
/// swapping; see `docs/geometry.md`, "CRS and axis order".
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FirstAxis {
    /// Easting or longitude first: x/y as written.
    EastOrLon,
    /// Northing or latitude first: y/x, so authority order needs a swap.
    NorthOrLat,
    /// Westing, southing, geocentric, ordinal and the like. Swapping the first
    /// two ordinates does not normalise these, so they are reported, not fixed.
    Other,
}

/// What kind of CRS this is, as EPSG classifies it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CrsKind {
    Geographic2d,
    Geographic3d,
    Projected,
    Geocentric,
    Vertical,
    Compound,
    Engineering,
    Derived,
}

impl CrsKind {
    /// Geographic CRSs take coordinates in degrees, which the range check and
    /// the dimension rule both care about.
    pub fn is_geographic(self) -> bool {
        matches!(self, CrsKind::Geographic2d | CrsKind::Geographic3d)
    }
}

/// One CRS from the EPSG dataset.
#[derive(Debug, Clone, PartialEq)]
pub struct CrsRecord {
    pub code: u32,
    /// EPSG's name, e.g. `"ETRS89 / PL-1992"`. Names change between EPSG
    /// releases; never match on this.
    pub name: &'static str,
    pub kind: CrsKind,
    pub first_axis: FirstAxis,
    /// Number of axes. A compound CRS reports horizontal plus vertical.
    pub dimension: u8,
    /// Size of the first axis's unit in metres, for CRSs measured in length
    /// (1.0 for metre, 0.3048… for foot). Used for `ArcByCenterPoint` radii.
    pub linear_unit_m: Option<f32>,
    /// Size of the first axis's unit in radians, for CRSs measured in angle.
    /// Distinguishes a CRS in gradians from one in degrees.
    pub angular_unit_rad: Option<f32>,
    /// EPSG's published area of use, in WGS 84 degrees, as
    /// `[south, west, north, east]`.
    ///
    /// This is EPSG's own bounding box, reproduced verbatim. It is deliberately
    /// *not* reprojected into the CRS's own units or axis order: doing that
    /// needs a projection engine, and the result would be our number rather
    /// than EPSG's. Callers that want it in axis order should use
    /// [`CrsRecord::area_in_axis_order`].
    pub area_wgs84: Option<[f32; 4]>,
    /// EPSG has retired this code. It is still resolvable, because real data
    /// keeps using retired codes for years.
    pub deprecated: bool,
}

impl CrsRecord {
    /// The area of use with its two horizontal bounds put in this CRS's own
    /// axis order, as `[min_first, min_second, max_first, max_second]`.
    ///
    /// Only meaningful for geographic CRSs, where the area of use and the
    /// coordinates share a unit. Returns `None` otherwise, so the range check
    /// abstains rather than comparing degrees against metres.
    pub fn area_in_axis_order(&self) -> Option<[f32; 4]> {
        if !self.kind.is_geographic() {
            return None;
        }
        let [south, west, north, east] = self.area_wgs84?;
        match self.first_axis {
            FirstAxis::NorthOrLat => Some([south, west, north, east]),
            FirstAxis::EastOrLon => Some([west, south, east, north]),
            FirstAxis::Other => None,
        }
    }
}

/// Look one EPSG code up. Includes deprecated codes.
pub fn get(code: u32) -> Option<&'static CrsRecord> {
    CRS.binary_search_by_key(&code, |record| record.code)
        .ok()
        .map(|index| &CRS[index])
}

// -------------------------------------------------------------------------
// PROJJSON
// -------------------------------------------------------------------------

/// `scripts/gen_crs_tables.py` writes this; `parse_header` documents the layout.
static PROJJSON_BLOB: &[u8] = include_bytes!("../data/projjson.bin");

const MAGIC: &[u8; 4] = b"XPJ1";
const SHARD_ENTRY: usize = 12; // offset, compressed length, raw length
const INDEX_ENTRY: usize = 8; // code, shard, line

struct Header {
    shards: usize,
    entries: usize,
}

impl Header {
    fn shard(&self, index: usize) -> (usize, usize, usize) {
        let at = 12 + index * SHARD_ENTRY;
        let read = |offset: usize| {
            u32::from_le_bytes(PROJJSON_BLOB[offset..offset + 4].try_into().unwrap()) as usize
        };
        (read(at), read(at + 4), read(at + 8))
    }

    /// Byte offset of the first zstd frame.
    fn blob_start(&self) -> usize {
        12 + self.shards * SHARD_ENTRY + self.entries * INDEX_ENTRY
    }

    /// Binary search of the code index, which the generator writes sorted.
    fn find(&self, code: u32) -> Option<(usize, usize)> {
        let base = 12 + self.shards * SHARD_ENTRY;
        let entry = |i: usize| {
            let at = base + i * INDEX_ENTRY;
            u32::from_le_bytes(PROJJSON_BLOB[at..at + 4].try_into().unwrap())
        };
        let (mut lo, mut hi) = (0usize, self.entries);
        while lo < hi {
            let mid = (lo + hi) / 2;
            match entry(mid).cmp(&code) {
                std::cmp::Ordering::Less => lo = mid + 1,
                std::cmp::Ordering::Greater => hi = mid,
                std::cmp::Ordering::Equal => {
                    let at = base + mid * INDEX_ENTRY;
                    let shard = u16::from_le_bytes(PROJJSON_BLOB[at + 4..at + 6].try_into().unwrap());
                    let line = u16::from_le_bytes(PROJJSON_BLOB[at + 6..at + 8].try_into().unwrap());
                    return Some((shard as usize, line as usize));
                }
            }
        }
        None
    }
}

fn header() -> &'static Header {
    static HEADER: OnceLock<Header> = OnceLock::new();
    HEADER.get_or_init(|| {
        assert_eq!(&PROJJSON_BLOB[..4], MAGIC, "data/projjson.bin is not a PROJJSON blob");
        let read = |offset: usize| {
            u32::from_le_bytes(PROJJSON_BLOB[offset..offset + 4].try_into().unwrap()) as usize
        };
        Header { shards: read(4), entries: read(8) }
    })
}

type ShardCache = Mutex<HashMap<usize, &'static [String]>>;

fn shard_cache() -> &'static ShardCache {
    static CACHE: OnceLock<ShardCache> = OnceLock::new();
    CACHE.get_or_init(Default::default)
}

/// PROJJSON for one EPSG code, as a JSON string.
///
/// Decompresses one shard (~115 KiB) on first use and keeps it, so looking up
/// many CRSs from the same region of the code space costs one decompression.
/// Returns `None` for codes EPSG does not define, and for the handful it
/// defines only as worked examples.
pub fn projjson(code: u32) -> Option<&'static str> {
    let header = header();
    let (shard, line) = header.find(code)?;

    let mut cache = shard_cache().lock().unwrap_or_else(|poisoned| poisoned.into_inner());
    let lines = match cache.get(&shard) {
        Some(lines) => *lines,
        None => {
            let (offset, compressed_len, raw_len) = header.shard(shard);
            let start = header.blob_start() + offset;
            let frame = &PROJJSON_BLOB[start..start + compressed_len];
            let raw = zstd::bulk::decompress(frame, raw_len).ok()?;
            let text = String::from_utf8(raw).ok()?;
            // Leaked deliberately: shards are immutable, bounded (one per 64
            // CRSs) and shared, so a `&'static` beats handing out clones.
            let lines: &'static [String] =
                Box::leak(text.lines().map(str::to_owned).collect::<Vec<_>>().into_boxed_slice());
            cache.insert(shard, lines);
            lines
        }
    };
    lines.get(line).map(String::as_str)
}
